### ISSUE TITLE
Uncaught TypeError concerning 'workers'

### ISSUE THREAD

**Issue by nmweaver** [noahtheprogrammer/fourcore#2]
Both 4RTM's original site and this miningcore-based website appear to be getting an identical error to one another. This occurs whenever `workers` is attempted to be read and might be the result of transitioning from older code.
```
Uncaught TypeError: Cannot read properties of null (reading 'workers')
    at Object.<anonymous> (fourcore.js:67:41)
    at c (jquery.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery.js:2:29072)
    at l (jquery.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.js:2:82355)
```

**Comment by nmweaver** [comment]
@valordk Do you have any ideas?

**Comment by valordk** [comment]
I can check serverside on 4rtm. What wallet are you trying with?
It's a common practice to give some steps to reproduce (STP) if the problem is consistent ;)

**Comment by valordk** [comment]
Remember, your project is public so are your comments. Hit me on discord if you don't want to write the details of the issue here.

**Comment by nmweaver** [comment]
I think I'll keep everything here in an official archive that we can come back to later if anything unexpected happens. This error seems to be replicated when I use the wallet below.

_RWXmeVTEJYNVp2htJQ97DMYvwytWUFTi8E_

**Comment by nmweaver** [comment]
@valordk I might have found the problem. Look at the JSON at the start of the miner API [here](https://4rtm.com/api/pools/Raptoreum-TESTNET/miners/). It's empty, so maybe it simply doesn't work because no one has mined to it. We might be able to fix it by getting a miner online and adding a catch statement to display something if the miner has not submitted anything yet.

**Comment by valordk** [comment]
Well it seems like an error on the client side. There has to be some null-guards implemented, to avoid calling properties of a null object if none is found. I have a similar error on 4rtm where data.performance gives an "NPE" if there is no data object returned.

**Comment by nmweaver** [comment]
> Well it seems like an error on the client side. There has to be some null-guards implemented, to avoid calling properties of a null object if none is found. I have a similar error on 4rtm where data.performance gives an "NPE" if there is no data object returned.

Alright. I'll work on putting in an error message to display and try-catch statements to fix the issue.

**Comment by nmweaver** [comment]
Ok, I've just fixed the problem in the latest commit. I'm going to close this issue now.
